import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, UserButton } from "@clerk/nextjs";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fitness World",
  description: "Generated by Hikmet Sinan CAKMAK",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              padding: "10px 20px",
              backgroundColor: "#f8f9fa",
              borderBottom: "1px solid #e0e0e0",
            }}
          >
            <div style={{ display: "flex", gap: "10px" }}>
              <Link href="/clubs" legacyBehavior>
                <a
                  style={{
                    padding: "10px 20px",
                    backgroundColor: "#0070f3",
                    color: "white",
                    borderRadius: "5px",
                    textDecoration: "none",
                  }}
                >
                  Clubs
                </a>
              </Link>
              <Link href="/my-bookings" legacyBehavior>
                <a
                  style={{
                    padding: "10px 20px",
                    backgroundColor: "#0070f3",
                    color: "white",
                    borderRadius: "5px",
                    textDecoration: "none",
                  }}
                >
                  My Bookings
                </a>
              </Link>
            </div>
            <h1
              style={{
                fontWeight: "bold",
                fontSize: "1.5em",
                margin: 0,
                position: "absolute",
                left: "50%",
                transform: "translateX(-50%)",
              }}
            >
              Welcome to Fitness World
            </h1>
            <SignedIn>
              <div style={{ display: "flex", alignItems: "center" }}>
                <UserButton showName />
              </div>
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
